### ISSUE TITLE
sticky elements

### ISSUE THREAD

**Issue by wortkotze** [morteza-fsh/puppeteer-full-page-screenshot#4]
Hi,

you mentioned
NOTE As this library scrolls down to take screenshots, sticky elements may appear multiple times on the final image. To fix this issue, you need to add custom styles to reset sticky positioned elements just before taking the screenshot.

is there a way to find the sticky elements in the viewport via puppeteer? so that we could hide them after making the screenshot?

**Comment by morteza-fsh** [comment]
Hi,

If you are aware of their class name, so you can hide them by adding style with puppeteer `addStyleTag` to the page just before taking the screenshot. Otherwise, you need to find all elements with position fixed or static on the page with puppeteer `evaluate`:

```javascript
let stickyElements = [...document.body.getElementsByTagName("*")].filter(
    x => ['fixed', 'sticky'].includes(getComputedStyle(x, null).getPropertyValue("position"))
);
```
 
Note that above snippet only finds elements by CSS position value thus, it unable to collect those elements that are positioned by JS

**Comment by wortkotze** [comment]
thx for the tip, its working fine, but as you mentioned its always a case by case definition
